stages:
  data_ingestion:
    cmd: python data_ingestion.py
    deps:
    - data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_Preprocessing:
    cmd: python data_Preprocessing.py
    deps:
    - data/raw
    - data_Preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python feature_engineering.py
    deps:
    - data/interim
    - feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/processed
  model_building:
    cmd: python model_building.py
    deps:
    - data/processed
    - model_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python model_evaluation.py
    deps:
    - models/model.pkl
    - model_evaluation.py
    metrics:
    - reports/metrics.json
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
